---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-sync.yaml
- gotk-components.yaml
- helm-repos/banzaicloud.yaml
- helm-repos/bitnami.yaml
- helm-repos/helm-stable.yaml
- helm-repos/prometheus-community.yaml
