---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: config
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: logging-base
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/logging-op/config
  prune: false
#  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: logging-base
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/base/logging-op/base
  prune: false
#  validation: client

