---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging-operator
spec:
  values:
    clusterOutputs:
    - name: cluster-kube-system
      spec:
        elasticsearch:
          host: elasticsearch.logging.svc.cluster.local
          port: 9200
          scheme: https
          ssl_verify: false
          ssl_version: TLSv1_2
          reconnect_on_error: true
          reload_on_failure: true
          reload_connections: false
          include_timestamp: true
          user: admin
          password:
            valueFrom:
              secretKeyRef:
                name: es-secrets
                key: password
      
          index_name: kube-system
          with_transporter_log: true
          buffer:
            chunk_limit_size: 4MB
            total_limit_size: 1024MB
            flush_mode: interval
            flush_interval: 30s
            flush_thread_count: 4
            retry_type: exponential_backoff
            retry_timeout: 1h
            retry_max_interval: 30s
            overflow_action: drop_oldest_chunk

